### ISSUE TITLE
actividad-5-diseno-de-estructura-de-libreria-dll-team-ola

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-team-ola#1]
//REPORTE PRACTICA 4//

[Reporte practica 4 libreria.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-team-ola/files/14645774/Reporte.practica.4.libreria.pdf)

**Comment by GerardoNR** [comment]
20
cumplio con todo lo que marca la rubricas

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
